# Creates packages
name: Create Release PR

permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch:
    inputs:
      level:
        description: 'Release level'
        required: true
        default: 'minor'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Protoc
        run: |
          PROTOC_VERSION=3.20.1
          PROTOC_ARCH=linux-x86_64
          PROTOC_ZIP=protoc-$PROTOC_VERSION-$PROTOC_ARCH.zip
          curl --retry 3 --retry-max-time 90 -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -OL https://github.com/protocolbuffers/protobuf/releases/download/v$PROTOC_VERSION/$PROTOC_ZIP
          sudo unzip -o $PROTOC_ZIP -d /usr/local bin/protoc
          sudo unzip -o $PROTOC_ZIP -d /usr/local 'include/*'
          rm -f $PROTOC_ZIP
          echo "PROTOC=/usr/local/bin/protoc" >> $GITHUB_ENV
          echo "PROTOC_INCLUDE=/usr/local/include" >> $GITHUB_ENV
      - name: Install cargo-release
        uses: taiki-e/install-action@v1
        with:
          tool: cargo-release
      - uses: cargo-bins/release-pr@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ inputs.level }}
          crate-name: ceramic-one